---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[odi-logging::default]
    data_bags_path: test/data_bags
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    attributes:
